### ISSUE TITLE
我收藏的连接怎么不见了呢？

### ISSUE THREAD

**Issue by gh-txgdr** [zhangjh/favLinksAdvise#10]

**Comment by zhangjh** [comment]
@gh-txgdr 什么现象？截图发我看下？你的用户名提供我帮你看下

**Comment by gh-txgdr** [comment]
![J%~ NMNVM{7X5XPB57OJ2V](https://user-images.githubusercontent.com/25651243/61201854-55ad8680-a718-11e9-8633-835956aad00c.png)

**Comment by gh-txgdr** [comment]
只有一个默认的

**Comment by gh-txgdr** [comment]
用户名 天下飞云

**Comment by gh-txgdr** [comment]
@zhangjh 怎么样了 ，数据丢了吗

**Comment by zhangjh** [comment]
@gh-txgdr 你再看下，一共44条，数据已经找回，为什么突然会丢失数据这个我还要排查。。

**Comment by gh-txgdr** [comment]
数据又丢了。。

**Comment by zhangjh** [comment]
@gh-txgdr 有什么操作吗？网站我很久没更新了，数据倒是可以找回，我怕是有什么bug被什么操作触发了

**Comment by zhangjh** [comment]
@gh-txgdr 你的数据已经找回，帮忙回忆下是否是在什么操作后引起了丢失

**Comment by gh-txgdr** [comment]
我记得我删除过一个收藏的地址条目

**Comment by gh-txgdr** [comment]
也有新添加过收藏地址
