### ISSUE TITLE
讨论，个人隐私采用什么机制？

### ISSUE THREAD

**Issue by ghost** [zhangjh/favLinksAdvise#2]
收藏夹一般都比较隐私性，请教一下个人对于个人隐私（一般存在后台数据）保护方面，实现的机制如何

**Comment by zhangjh** [comment]
@shwangjjwjj 个人信息如密码，是通过加盐md5存放的，至于收藏的链接就没有加密了，否则显示的时候还要解密，业务上可行性不高

**Comment by zhangjh** [comment]
@shwangjjwjj 先关闭了，如果有什么问题或建议欢迎继续提issue
