### ISSUE TITLE
导出和移动功能

### ISSUE THREAD

**Issue by sisyphus45** [zhangjh/favLinksAdvise#4]
先感谢作者做出的这么方便的网络收藏夹。没发现有导出功能，也没发现移动分类标签的功能，如果没有这两项功能，方便添加吗。担心该空间的持续性～～

**Comment by zhangjh** [comment]
@sisyphus45 非常感谢你的建议，后续会添加上导出功能

**Comment by zhangjh** [comment]
@sisyphus45 导出功能已经添加
页面上点击导出后会导出一份html文件，为Chrome的书签导出格式。

在Chrome下，使用书签的导入功能，选择以前导出的文件，可以将导出的url导入到Chrome书签中，如图所示。其他各大浏览器也都支持Chrome备份书签，不赘述
![image](https://user-images.githubusercontent.com/3371714/46913739-66806e80-cfc5-11e8-99bc-d3f1b19008e2.png)
